server:
  port: 80

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
          facebook:
            clientId: ${FACEBOOK_CLIENT_ID}
            clientSecret: ${FACEBOOK_CLIENT_SECRET}
#          custom-client:
#            client-id:
#            client-secret:
#            redirect_uri:
#            authorization-grant-type:
#        provider:
#          custom-client:
#            token-uri:
#            authorization-uri:


#logging:
#  level:
#    org.springframework.security: TRACE